requires 'Tenjin', 0.070001;
requires 'Try::Tiny';
requires 'Mojolicious', 6.44;
requires 'Mojolicious::Plugin::Authentication';
requires 'Mojolicious::Plugin::Config';
requires 'HTML::Entities';
requires 'JSON';
requires 'File::Slurp';
requires 'IO::Async::Loop';
requires 'Net::Async::CassandraCQL';
requires 'Protocol::CassandraCQL';
